export const RECEIVE_ISSUES = 'RECEIVE_ISSUES';
export const UPDATE_METADATA = 'UPDATE_METADATA';
export const SET_SELECTED_ISSUE_DATA = 'SET_SELECTED_ISSUE_DATA';
export const SET_SELECTED_ISSUE_COMMENTS = 'SET_SELECTED_ISSUE_COMMENTS';
